# Generated by Django 3.1.3 on 2020-11-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books2', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
